 const cards = [
  "brain",
  "brain-medicine",
  "brain-virus",
  "stomach",
  "stomach-medicine",
  "stomach-virus",
  "pelvis",
  //"pelvis-medicine",
  //"pelvis-virus",
  "heart",
  "heart-medicine",
  "heart-virus",
  "brain",
  "brain-medicine",
  "brain-virus",
  "stomach",
  "stomach-medicine",
  "stomach-virus",
  "pelvis",
  //"pelvis-medicine",
  //"pelvis-virus",
  "heart",
  // "heart-medicine",
  // "heart-virus",
  "brain",
  // "brain-medicine",
  // "brain-virus",
  "stomach",
  // "stomach-medicine",
  // "stomach-virus",
  "pelvis",
  //"pelvis-medicine",
  //"pelvis-virus",
  "heart",
  // "heart-medicine",
  // "heart-virus",
  "brain",
  // "brain-medicine",
  // "brain-virus",
  "stomach",
  // "stomach-medicine",
  // "stomach-virus",
  "pelvis",
  //"pelvis-medicine",
  //"pelvis-virus",
  "heart",
  // "heart-medicine",
  // "heart-virus",
]
export default cards